"""The symptom fingerprint — the Memory Bank's primary key.

Load-bearing, and the reason it lives in `common/` rather than in the Triage
package: Triage mints the key, Memory persists under it, Diagnosis looks up by it.
All three must compute it identically or the memory hit silently never happens.

DETERMINISM IS THE WHOLE CONTRACT. No model writes this key. Same failure class
weeks apart must produce byte-identical output, so every input is normalised and
the input set is deliberately narrow: things that are stable across two
occurrences of the same failure, and nothing else.

Explicitly NOT hashed, because they differ between occurrences of one failure class:
  - incident_id, timestamps, observed values, revision names, trace/span ids
  - anything model-authored
  - anything from an untrusted field

Changing the input set invalidates every signature already in the Memory Bank.
If it must change, bump FINGERPRINT_VERSION and treat old signatures as a
different keyspace rather than silently re-keying them.
"""

from __future__ import annotations

import hashlib
import re

from agents.common.schemas import FingerprintInputs

FINGERPRINT_VERSION = 1
_FINGERPRINT_LEN = 16

_UNKNOWN = "unknown"

# Cloud Monitoring condition display names carry churn that is not part of the
# failure class: an autogenerated suffix, the policy's own name, a threshold that
# was retuned between occurrences. Strip all of it.
_UUIDISH = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I)
_NUMERIC = re.compile(r"\d+(?:\.\d+)?")
_NON_KEY = re.compile(r"[^a-z0-9]+")


def normalise(value: str | None) -> str:
    """Collapse a free-form GCP label to a stable key token.

    Lowercase, strip UUID-ish and numeric runs, squash separators. `None` and
    empty both become "unknown" so a missing field never silently shifts the hash
    to whatever happened to be adjacent.
    """
    if not value:
        return _UNKNOWN
    v = value.strip().lower()
    v = _UUIDISH.sub("", v)
    v = _NUMERIC.sub("", v)
    v = _NON_KEY.sub("-", v).strip("-")
    return v or _UNKNOWN


def normalise_metric(metric_type: str | None) -> str:
    """Metric types are already stable identifiers — keep their shape, drop the host.

    `logging.googleapis.com/user/classifier_errors` -> `user/classifier_errors`
    so that a metric surviving a rename of its exporting host still matches.
    """
    if not metric_type:
        return _UNKNOWN
    v = metric_type.strip().lower()
    if "/" in v:
        head, _, tail = v.partition("/")
        if "." in head:  # a hostname prefix, not a path segment
            v = tail
    return _NON_KEY.sub("-", v).strip("-") or _UNKNOWN


def compute(inputs: FingerprintInputs) -> str:
    """Hash the four stable inputs. Returns 16 lowercase hex chars.

    16 chars of SHA-256 is ~64 bits — collision-safe for an incident corpus by an
    enormous margin, and short enough to eyeball in a log line or a trace attribute.
    """
    key = "|".join(
        (
            str(FINGERPRINT_VERSION),
            normalise(inputs.service),
            normalise_metric(inputs.metric),
            normalise(inputs.condition),
            inputs.direction,
        )
    )
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:_FINGERPRINT_LEN]


def infer_direction(
    observed: float | None, threshold: float | None, condition: str | None = None
) -> str:
    """Which way the metric moved. Part of the key, so it must be derived, not guessed.

    A service erroring at 31% against a 5% ceiling and a service whose throughput
    fell through a floor are different failure classes even on the same metric;
    folding them into one key would produce a wrong memory hit, which is worse
    than a miss.
    """
    text = (condition or "").lower()
    if "absent" in text or "no data" in text:
        return "absent"
    if observed is None or threshold is None:
        if "below" in text or "less" in text or "drop" in text:
            return "drop"
        if "above" in text or "greater" in text or "exceed" in text:
            return "spike"
        return "unknown"
    if observed > threshold:
        return "spike"
    if observed < threshold:
        return "drop"
    return "unknown"


def build(
    *,
    service: str | None,
    metric: str | None,
    condition: str | None,
    observed: float | None = None,
    threshold: float | None = None,
) -> tuple[str, FingerprintInputs]:
    """Convenience path used by Triage: raw alert fields in, (hash, inputs) out."""
    inputs = FingerprintInputs(
        service=service or _UNKNOWN,
        metric=metric or _UNKNOWN,
        condition=condition or _UNKNOWN,
        direction=infer_direction(observed, threshold, condition),
    )
    return compute(inputs), inputs
